# Generated by Django 5.2.17 on 2026-08-16 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="avaliable_copies",
            new_name="available_copies",
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="books",
                to="books.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="books.category"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
