# Generated by Django 5.2.17 on 2026-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_rename_avaliable_copies_book_available_copies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
